{
  imports = [
    ./pi
    ./obs.nix
    ./steam.nix
    ./fish
    ./hypr
    ./rbw.nix
    ./mako.nix
    ./clipnotify.nix
    ./swayosd.nix
    ./zed.nix
    ./alacritty.nix
    ./helix.nix
    ./calendar.nix
    ./wofi.nix
    ./fastfetch.nix
    ./glance.nix
    ./waybar.nix
    ./neovim.nix
    ./kitty.nix
    ./qutebrowser.nix
    ./email.nix
    ./aerc/aerc.nix
    ./hytale.nix
    ./fuzzel.nix
    ./noctalia.nix
    ./spicetify.nix
    ./mangohud.nix
    ./firefox.nix
    ./thunderbird
  ];
}
