{
  config,
  lib,
  pkgs,
  ...
}: let
  profile = "ywbct64a.default";

  profilesIni = pkgs.writeText "thunderbird-profiles.ini" ''
    [Profile0]
    Name=default
    IsRelative=1
    Path=${profile}
    Default=1

    [General]
    StartWithLastProfile=1
    Version=2
  '';

  userJs = pkgs.writeText "thunderbird-user.js" ''
    // Generated by Home Manager.
    user_pref("browser.search.region", "BR");
    user_pref("browser.theme.content-theme", 0);
    user_pref("browser.theme.toolbar-theme", 0);
    user_pref("calendar.timezone.local", "America/Sao_Paulo");
    user_pref("calendar.timezone.useSystemTimezone", true);
    user_pref("extensions.activeThemeID", "seoul-dark@mkirc.themes.thunderbird.net");
    user_pref("extensions.filtaquilla.removeFlagged.enabled", true);
    user_pref("extensions.filtaquilla.removeKeyword.enabled", true);
    user_pref("mail.account.account2.server", "server4");
    user_pref("mail.account.account4.identities", "id1");
    user_pref("mail.account.account4.server", "server5");
    user_pref("mail.account.lastKey", 4);
    user_pref("mail.accountmanager.accounts", "account4,account2");
    user_pref("mail.accountmanager.defaultaccount", "account4");
    user_pref("mail.accountmanager.localfoldersserver", "server4");
    user_pref("mail.identity.id1.doBcc", false);
    user_pref("mail.identity.id1.draft_folder", "mailbox://nobody@Local%20Folders/Drafts");
    user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
    user_pref("mail.identity.id1.fcc_folder", "imap://me%40lrd.rs@email-ssl.com.br/Sent");
    user_pref("mail.identity.id1.fcc_folder_picker_mode", "0");
    user_pref("mail.identity.id1.fullName", "Fernando Marques");
    user_pref("mail.identity.id1.htmlSigText", "Atenciosamente,\nFernando Marques.");
    user_pref("mail.identity.id1.reply_on_top", 1);
    user_pref("mail.identity.id1.sig_bottom", false);
    user_pref("mail.identity.id1.smtpServer", "smtp3");
    user_pref("mail.identity.id1.stationery_folder", "imap://me%40lrd.rs@email-ssl.com.br/Templates");
    user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
    user_pref("mail.identity.id1.useremail", "me@lrd.rs");
    user_pref("mail.identity.id1.valid", true);
    user_pref("mail.root.imap", "${config.home.homeDirectory}/.thunderbird/${profile}/ImapMail");
    user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
    user_pref("mail.root.none", "${config.home.homeDirectory}/.thunderbird/${profile}/Mail");
    user_pref("mail.root.none-rel", "[ProfD]Mail");
    user_pref("mail.server.server4.directory", "${config.home.homeDirectory}/.thunderbird/${profile}/Mail/Local Folders");
    user_pref("mail.server.server4.directory-rel", "[ProfD]Mail/Local Folders");
    user_pref("mail.server.server4.hostname", "Local Folders");
    user_pref("mail.server.server4.name", "Local Folders");
    user_pref("mail.server.server4.spamActionTargetAccount", "mailbox://nobody@Local%20Folders");
    user_pref("mail.server.server4.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
    user_pref("mail.server.server4.type", "none");
    user_pref("mail.server.server4.userName", "nobody");
    user_pref("mail.server.server5.ageLimit", 30);
    user_pref("mail.server.server5.authMethod", 3);
    user_pref("mail.server.server5.check_new_mail", true);
    user_pref("mail.server.server5.directory", "${config.home.homeDirectory}/.thunderbird/${profile}/ImapMail/email-ssl.com.br");
    user_pref("mail.server.server5.directory-rel", "[ProfD]ImapMail/email-ssl.com.br");
    user_pref("mail.server.server5.downloadByDate", false);
    user_pref("mail.server.server5.downloadUnreadOnly", false);
    user_pref("mail.server.server5.hostname", "email-ssl.com.br");
    user_pref("mail.server.server5.login_at_startup", true);
    user_pref("mail.server.server5.max_cached_connections", 5);
    user_pref("mail.server.server5.name", "me@lrd.rs");
    user_pref("mail.server.server5.namespace.personal", "\"INBOX.\"");
    user_pref("mail.server.server5.port", 993);
    user_pref("mail.server.server5.socketType", 3);
    user_pref("mail.server.server5.spamActionTargetAccount", "imap://me%40lrd.rs@email-ssl.com.br");
    user_pref("mail.server.server5.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
    user_pref("mail.server.server5.timeout", 29);
    user_pref("mail.server.server5.type", "imap");
    user_pref("mail.server.server5.userName", "me@lrd.rs");
    user_pref("mail.shell.checkDefaultClient", false);
    user_pref("mail.smtp.defaultserver", "smtp3");
    user_pref("mail.smtpserver.smtp3.authMethod", 3);
    user_pref("mail.smtpserver.smtp3.hostname", "email-ssl.com.br");
    user_pref("mail.smtpserver.smtp3.port", 465);
    user_pref("mail.smtpserver.smtp3.try_ssl", 3);
    user_pref("mail.smtpserver.smtp3.type", "smtp");
    user_pref("mail.smtpserver.smtp3.username", "me@lrd.rs");
    user_pref("mail.smtpservers", "smtp3");
    user_pref("mail.tabs.drawInTitlebar", false);
    user_pref("mail.threadpane.listview", 1);
    user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
    user_pref("mailnews.start_page.url", "https://codeberg.org/Rakki");
    user_pref("spellchecker.dictionary", "en-US,pt-BR");
  '';
in {
  programs.thunderbird = {
    enable = true;
    languagePacks = ["pt-BR"];
    policies.ExtensionSettings = {
      "filtaquilla@mesquilla.com" = {
        installation_mode = "force_installed";
        install_url = "https://addons.thunderbird.net/thunderbird/downloads/file/1048356/filtaquilla-6.2.2-tb.xpi";
      };
      "replywithheader@myjeeva.com" = {
        installation_mode = "force_installed";
        install_url = "https://addons.thunderbird.net/thunderbird/downloads/file/1042881/replywithheader-3.3.1-tb.xpi";
      };
      "seoul-dark@mkirc.themes.thunderbird.net" = {
        installation_mode = "force_installed";
        install_url = "https://addons.thunderbird.net/thunderbird/downloads/file/1020548/seoul_dark-1.3-tb.xpi";
      };
      "macchitiounofficial@addons.thunderbird.net" = {
        installation_mode = "normal_installed";
        install_url = "https://addons.thunderbird.net/thunderbird/downloads/file/1040515/catppuccin_macchiatio_unofficial-1.1-tb.xpi";
      };
      "pt-BR@dellalibera.sf.net" = {
        installation_mode = "force_installed";
        install_url = "https://addons.thunderbird.net/thunderbird/downloads/file/1012599/verificador_ortografico_para_portugues_do_brasil-2.5-3.2.13.1webext.xpi";
      };
    };
  };

  # The profile is persisted as a bind mount, so regular files survive activation.
  home.activation.configureThunderbird = lib.hm.dag.entryAfter ["writeBoundary"] ''
    ${pkgs.coreutils}/bin/install -Dm600 ${profilesIni} "$HOME/.thunderbird/profiles.ini"
    ${pkgs.coreutils}/bin/install -Dm600 ${userJs} "$HOME/.thunderbird/${profile}/user.js"
    ${pkgs.coreutils}/bin/rm -f "$HOME/.thunderbird/installs.ini"
  '';
}
